---
- name: "Check if auth file exists"
  stat:
    path: "{{ kafka_path }}/config/ansible-auth-{{kafka_admin_username}}.properties"
  register: file

- name: Setup New config file for auth user
  template:
    src: auth.properties.j2
    dest: "{{ kafka_path }}/config/ansible-auth-{{kafka_admin_username}}.properties"
    mode: 0644
    owner: kafka
    group: kafka
  when: not file.stat.exists

- name: Create Kafka User {{new_kafka_user_username}}ß
  command: "{{kafka_path}}/bin/kafka-configs.sh --bootstrap-server localhost:9092 --alter --add-config 'SCRAM-SHA-256=[password={{new_kafka_user_password}}],SCRAM-SHA-512=[password={{new_kafka_user_password}}]' --entity-type users --entity-name {{new_kafka_user_username}} --command-config {{kafka_path}}/config/ansible-auth-{{kafka_admin_username}}.properties"
  register: kafka_user_created

- name: Display Kafka User Created
  debug: 
    var: kafka_user_created.stdout
