---
- name: "Check if auth file exists"
  stat:
    path: "{{ kafka_path }}/config/ansible-auth-{{kafka_admin_username}}.properties"
  register: file

- name: Setup New config file for auth user
  template:
    src: auth.properties.j2
    dest: "{{ kafka_path }}/config/ansible-auth-{{kafka_admin_username}}.properties"
    mode: 0644
    owner: kafka
    group: kafka
  when: not file.stat.exists

- name: Check Kafka User List
  command: "{{kafka_path}}/bin/kafka-configs.sh --bootstrap-server localhost:9092 --describe --all --entity-type users --command-config {{kafka_path}}/config/ansible-auth-{{kafka_admin_username}}.properties"
  register: kafka_user_list

- name: Display Kafka User List
  debug: 
    var: kafka_user_list.stdout
