---
- include: facts.yml

- include: kafka_topic_list.yml
  tags: kafka_topic_list
  
- include: kafka_topic_describe.yml
  tags: kafka_topic_describe

- include: kafka_topic_create.yml
  tags: kafka_topic_create

- include: kafka_topic_remove.yml
  tags: kafka_topic_remove